#!/usr/bin/python3
from dotenv import load_dotenv, set_key, find_dotenv
import os
import requests
import base64
import uuid

# Load environment variables from .env file
dotenv_path = find_dotenv()
load_dotenv()
API_KEY = os.getenv('API_KEY')
SECRET_KEY = os.getenv('SECRET_KEY')
CONTRACT_CODE = os.getenv('CONTRACT_CODE')



# 1. Generate access token
def generate_access_token():
    credentials = f"{API_KEY}:{SECRET_KEY}"
    url = "https://sandbox.monnify.com/api/v1/auth/login"
    encoded_base64_credentials = base64.b64encode(credentials.encode("ascii")).decode("ascii")
    headers = {
        "Authorization" : f"Basic {encoded_base64_credentials}"
    }
    response = requests.post(url, headers=headers)
    print(response.json())
    return response.json().get('responseBody', {}).get('accessToken')


set_key(dotenv_path, "JWT", generate_access_token()) # create or update JWT in .env file
JWT = os.getenv('JWT')
# Dont forget to set take note of expiry time of JWT
########

class User:
    def __init__(self, full_name, email, mobile_no, bvn, nin, dob, password_hash):
        self.full_name = full_name
        self.email = email
        self.mobile_no = mobile_no
        self.bvn = bvn
        self.nin = nin
        self.dob = dob
        self.password_hash = password_hash

    def store_user(self):
        """
        Stores the user instance into the 'users' table in cashely.db.
        Returns the inserted user's ID (auto-generated by SQLite).
        """
        conn = sqlite3.connect('cashely.db')
        cursor = conn.cursor()

        try:
            cursor.execute('''
                INSERT INTO users (full_name, email, mobile_no, bvn, nin, dob, password_hash)
                VALUES (?, ?, ?, ?, ?, ?, ?)
            ''', (
                self.full_name,
                self.email,
                self.mobile_no,
                self.bvn,
                self.nin,
                self.dob,
                self.password_hash
            ))
            conn.commit()
            user_id = cursor.lastrowid  # Get the auto-generated ID
            return user_id
        except sqlite3.IntegrityError as e:
            # Handle duplicate email, BVN, or NIN
            print(f"Error storing user: {e}")
            return None
        finally:
            conn.close()
        
        def create_wallet(self, user_id):
            """
            Creates a wallet for the user with the given user_id.
            Initializes the wallet balance to 0.0.
            """
            pass

        def create_virtual_account(self, name, email, bvn, id):
            """
            Creates a virtual account for the user.
            """
            url = "https://sandbox.monnify.com/api/v2/bank-transfer/reserved-accounts"
            headers={
            "Authorization": f"Bearer {JWT}",
            "Content-Type": "application/json"
            }
            params = {
            "accountReference": f"{name}_{id}",
            "accountName": name,
            "currencyCode": "NGN",
            "contractCode": CONTRACT_CODE,
            "customerEmail": email,
            "customerName": name,
            "bvn": bvn,
            "getAllAvailableBanks": "true",
            "preferredBanks": [
                "50515"
            ]
            }
            
            response = requests.post(url, headers=headers, json=params)
            if response.status_code == 200:
                response_body = response.json().get('responseBody', {})
                
                # 1. Seclude the keys from the response body
                monnify_reservation_id = response_body.get('reservationReference')
                source_created_at = response_body.get('createdOn')
                
                accounts = response_body.get('accounts', [])
                if not accounts:
                    print("Error: API response did not contain account details.")
                    return # Exit if no account info
                    
                account_number = accounts[0].get('accountNumber')
                bank_name = accounts[0].get('bankName')
                bank_code = accounts[0].get('bankCode')

                # 2. Open the database connection
                conn = sqlite3.connect('cashely.db')
                cursor = conn.cursor()

                try:
                    # 3. Get the wallet_id for this user (assuming one wallet per user for now)
                    cursor.execute("SELECT id FROM wallets WHERE user_id = ?", (user_id,))
                    result = cursor.fetchone()
                    
                    if not result:
                        print(f"Error: No wallet found for user_id {user_id}. Cannot create virtual account.")
                        return # Exit if no wallet exists

                    wallet_id = result[0]

                    # 4. Prepare the SQL INSERT statement
                    sql = '''
                        INSERT INTO virtual_accounts (
                            user_id, 
                            wallet_id, 
                            bank_name, 
                            bank_code, 
                            account_number, 
                            monnify_reservation_id, 
                            created_at
                        ) VALUES (?, ?, ?, ?, ?, ?, ?)
                    '''
                    
                    # 5. Execute the query with the data
                    cursor.execute(sql, (
                        user_id,
                        wallet_id,
                        bank_name,
                        bank_code,
                        account_number,
                        monnify_reservation_id,
                        source_created_at  # Using the timestamp from Monnify's API
                    ))
                    
                    # 6. Commit the changes to save them
                    conn.commit()
                    print("Successfully created and saved virtual account to the database.")

                except sqlite3.Error as e:
                    print(f"Database error: {e}")
                finally:
                    # 7. Close the connection
                    conn.close()

            else:
                print(f"Failed to create virtual account. Status: {response.status_code}, Response: {response.text}")

            

# 2. VERIFY BVN AND NIN
def verify_bvn(bvn, name, dob, mobile_no):
    
    url = "https://sandbox.monnify.com/api/v1/vas/bvn-details-match"
    headers = {
        "Authorization": f"Bearer {JWT}",
        "Content-Type": "application/json"
    }

    # handle parameters during signup stage to be sent as arguments here
    params = {
      "bvn": bvn,
      "name": name,
      "dateOfBirth": dob,
      "mobileNo": mobile_no
    }
    response = requests.post(url, headers=headers, json=params)
    message = response.json().get('responseMessage')
    if message != "success":
        return message

def verify_nin(nin):    
    url = "https://sandbox.monnify.com/api/v1/vas/nin-details"
    headers = {
        "Authorization": f"Bearer {JWT}",
        "Content-Type": "application/json"
    }

    # handle parameters during signup stage to be sent as arguments here
    params = {
        "nin": nin
        }
    response = requests.post(url, headers=headers, json=params)
    message = response.json().get('responseMessage')
    if message != "success":
        return message

# BVN and NIN verification can only be used in Live mode and has a cost attached to it
##########

# Signup  User

# 4. Create Virtual Account
def create_virtual_account(account_name, customer_email):
    id = str(uuid.uuid4())
    
